require 'rake/testtask'
begin
  require 'rspec/core/rake_task'
rescue LoadError
  # rspec not installed
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end

if defined?(RSpec::Core::RakeTask)
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = 'spec/*_spec.rb'
  end
end

task :default  => :test
